# web port
server:
  port: 8301

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:9201/
      user: admin
      password: 123456
#      rememberMe: 1