# web port
server:
  port: 8201

# log config
logging:
  config: classpath:logback.xml
  path: /app/datax-web/logs/applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://172.16.35.55:9201/
    executor:
      appname: datax-executor
      ip: 172.16.35.55
      port: 9995
      ### job log path
      logpath: /app/datax-web/logs/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken: qwertyuiop

  executor:
    #jsonpath: D:\\temp\\executor\\json\\
    jsonpath: /app/datax-web/temp/datax/executor/json

  #pypath: F:\tools\datax\bin\datax.py
  pypath: /app/datax/bin/datax.py