# web port
server:
  port: 8201

# log config
logging:
  config: classpath:logback.xml
  path: ./logs/applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:9201/
    executor:
      appname: datax-executor
      ip: 127.0.0.1
      port: 9999
      ### job log path
      logpath: ./logs/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken: qwertyuiop

  executor:
    #jsonpath: D:\\temp\\executor\\json\\
    jsonpath: /Users/ada/Documents/work/temp/datax/executor/json

  #pypath: F:\tools\datax\bin\datax.py
  pypath: /Users/ada/Documents/work/tools/datax/bin/datax.py