FROM harbor.dap.local/library/metrics-datax-base:3

#时区
RUN echo "Asia/Shanghai" > /etc/timezone

#参数
ARG OUT_DIR_DATAX_EXECUTOR

# 将上传到对应目录下
COPY ${OUT_DIR_DATAX_EXECUTOR}/conf /opt/datax-web/datax-executor/conf/
COPY ${OUT_DIR_DATAX_EXECUTOR}/datax-executor-2.1.3-SNAPSHOT.jar /opt/datax-web/datax-executor

#使用ENTRYPOINT启动脚本
EXPOSE 8201 9999
ENTRYPOINT ["java","-Dspring.config.location=file:/opt/datax-web/datax-executor/conf/","-jar","/opt/datax-web/datax-executor/datax-executor-2.1.3-SNAPSHOT.jar","--spring.profiles.active=demo"]

